### PR TITLE
Add `from_enviroment()` from `rest_tools` and Upgrade

### PR DESCRIPTION
**Pull request by ric-evans**
1. Copy-Paste
2. Upgrade default bool-parsing method to use `distutils.util.strtobool`
   - Plan to add a redirect in `rest_tools/server/config.py` ~with `legacy_bool=True` option~ for backwards-compatibility

### CODE REVIEW

**Comment by ric-evans** [comment]
related: https://github.com/WIPACrepo/rest-tools/issues/25

**Comment by dsschult** [comment]
Is there a reason for using `strtobool`?  The main difference is that it raises `ValueError` if it doesn't match, instead of defaulting to `false`.

**Comment by ric-evans** [comment]
> Is there a reason for using `strtobool`? The main difference is that it raises `ValueError` if it doesn't match, instead of defaulting to `false`.

I've seen it recommended as a way to parse environment variables. It also adds "on"/"off", but the biggest sell is that it protects against false negatives (intentional or typos): "tru", "2", etc.

**Comment by dsschult** [comment]
> > Is there a reason for using `strtobool`? The main difference is that it raises `ValueError` if it doesn't match, instead of defaulting to `false`.
> 
> I've seen it recommended as a way to parse environment variables. It also adds `"on"`/`"off"`, but the biggest sell is that it protects against false negatives (intentional or typos): `"tru"`, `"2"`, etc.

Not sure I'm a fan of the error message that will return, for debugging purposes.  Also, one key point: it returns an int instead of a bool.  You should at least do a cast after that.

@blinkdog what are your thoughts about raising an exception?

**Comment by ric-evans** [comment]
> it returns an int instead of a bool.

Well, that's a major design flaw! The doc block I get says it's a bool, but it's definitely not.

> Not sure I'm a fan of the error message that will return, for debugging purposes.

I'm in favor of wrapping the exception with our own message.

**Review by dsschult — APPROVED** [review]

**Review by blinkdog — APPROVED** [review]
LGTM!

**Pull request merged**
